name: titiler-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.10.*
  - google-auth
  - google-cloud-secret-manager
  - google-cloud-logging
  - gdal
  - fastapi <0.108.0 #to avoid AssertionError bug w/ titiler
  - uvicorn
  - pip
  - pip:
      - titiler.core
      - python-multipart
