image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      mamba env create -f environment.yml
      mkdir data
      curl -o data/baer_classifications.zip https://storage.cloud.google.com/national_park_service/joshua_tree/BAER_Classifications/Fire_data_bundles_tiAWDyiXROUl0fjFRr8r.zip
      unzip data/baer_classifications.zip -d data
  - command: |
      conda activate burn-severity