name: burn-severity

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - gdal=2.*
  - numpy=1.*
  - matplotlib
  - geopandas= 0.*
  - rasterio= 1.*
  - ipython
  - jupyter
