name: burn-severity

channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - rich
  - rich-with-jupyter
  - gdal
  - numpy
  - matplotlib
  - geopandas
  - rasterio
  - ipython
  - jupyter
  - pystac-client
  - boto3
  - planetary-computer
