name: burn-severity-prod

channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - rioxarray
  - stackstac
  - gdal
  - numpy
  - geopandas
  - rasterio
  - ipython
  - pystac-client
  - planetary-computer
  - flask
  - pysftp
  - chalice