name: burn-severity

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gdal=2.2.4
  - numpy=1.15.*
  - matplotlib
  - geopandas= 0.4.0
  - rasterio= 1.0.*
  - ipython
  - jupyter
