name: burn-severity

channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.10.*
  - google-auth
  - google-cloud-secret-manager
  - google-cloud-logging
  - google-cloud-tasks
  - ipykernel
  - rioxarray
  - stackstac
  - contextily
  - rich
  - rich-with-jupyter
  - gdal
  - numpy
  - matplotlib
  - geopandas
  - rasterio
  - seaborn
  - ipython
  - jupyter
  - pystac-client
  - markdown
  - boto3
  - planetary-computer
  - fastapi <0.108.0 #to avoid AssertionError bug w/ titiler
  - uvicorn
  - pip
  - pytest
  - pyarrow
  - smart_open
  - sentry-sdk[fastapi]
  - sphinx
  - sklearn
  - pip:
      - titiler.core
      - python-multipart
