name: dev-addon-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - contextily
  - dask
  - debugpy
  - ipykernel
  - ipython
  - jupyter
  - markdown
  - python-multipart
  - rich
  - rich-with-jupyter
  - seaborn
  - sphinx
  - uvicorn
