version: "3.8"
services:
  titiler:
    build:
      context: ../
      dockerfile: .devcontainer/titiler/dev.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud


  burn_backend:
    build:
      context: ../
      dockerfile: .devcontainer/burn_backend/dev.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
    ports:
      - 5050:5050
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud
    depends_on:
      - titiler
