version: "3.8"
services:
  titiler:
    build:
      context: ../
      dockerfile: .deployment/titiler/prod.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
        - ENV=LOCAL
    ports:
      - 8081:8080 # FastAPI
      - 8678:8678 # Debugpy
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  burn_backend:
    build:
      context: ../
      dockerfile: .deployment/burn_backend/prod.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
        - ENV=LOCAL
    ports:
      - 5051:5050 # FastAPI
      - 5678:5678 # Debugpy
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"