version: "3.8"
services:
  titiler:
    build:
      context: ../
      dockerfile: .deployment/titiler/prod.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
    ports:
      - 8081:8080
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud
    env_file:
      - .env

  burn_backend:
    build:
      context: ../
      dockerfile: .deployment/burn_backend/prod.Dockerfile
      args:
        - DEVCONTAINER_SERVICE=${DEVCONTAINER_SERVICE}
    ports:
      - 5051:5050
    volumes:
      - type: bind
        source: ${LOCAL_ENV_HOME}/.aws
        target: /root/.aws
      - type: bind
        source: ${LOCAL_ENV_HOME}/.config/gcloud
        target: /root/.config/gcloud
    env_file:
      - .env
