name: burn-severity

channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.10.*
  - ipykernel
  - rioxarray
  - stackstac
  - contextily
  - rich
  - rich-with-jupyter
  - gdal
  - numpy
  - matplotlib
  - geopandas
  - rasterio
  - seaborn
  - ipython
  - jupyter
  - pystac-client
  - boto3
  - planetary-computer
  - flask
  - pysftp
  - chalice