name: Push and Deploy to Cloud Run
on: 
  push:
    branches:
      - dev

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/natl-park-service/locations/global/workloadIdentityPools/github/providers/oidc-provider' # Update with your provider
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - id: Deploy
      name: Build and Deploy
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE
        gcloud beta run deploy $SERVICE --image gcr.io/$PROJECT_ID/$SERVICE --platform managed