name: Push and Deploy to Cloud Run
on: 
  push:
    branches:
      - dev

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: 'actions/checkout@v4'

    - name: Setup Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/113009620257/locations/global/workloadIdentityPools/github/providers/oidc-provider'
        project_id: 'dse-nps'
        service_account: 'github-actions-service-account@dse-nps.iam.gserviceaccount.com'

    - name: Build and Deploy
      run: |
        gcloud builds submit --tag gcr.io/113009620257/burn-backend
        gcloud beta run deploy burn-backend --image gcr.io/113009620257/burn-backend --platform managed
