name: Push and Deploy to Cloud Run
on: 
  push:
    branches:
      - dev

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: 'actions/checkout@v4'

    - name: Setup Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/dse-nps/locations/global/workloadIdentityPools/github/providers/oidc-provider'
        project_id: 'dse-nps'
        service_account: 'github-actions-service-account@dse-nps.iam.gserviceaccount.com'

    - id: Deploy
      name: Build and Deploy
      run: |
        gcloud builds describe '123-456-789'
