name: Push and Deploy to Cloud Run
on: 
  push:
    branches:
      - dev

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: 'actions/checkout@v4'

    - name: Setup Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/natl-park-service/locations/global/workloadIdentityPools/github/providers/oidc-provider'
        project_id: 'natl-park-service'
        service_account: 'github-actions-service-account@natl-park-service.iam.gserviceaccount.com'

    - name: Build and Deploy
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE
        gcloud beta run deploy $SERVICE --image gcr.io/$PROJECT_ID/$SERVICE --platform managed