name: Build Prod and PyTest

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t prod -f .deployment/prod.Dockerfile .

      - name: Run tests
        run: docker run prod /bin/bash -c "pip install pytest && pytest"
